server:
  addr: ":8080"

redis:
  addr: "redis:6379"   # use "redis:6379" when running via docker-compose
  db: 0
  password: ""

identity:
  # one of: header:<Header-Name> | ip
  source: "header:X-API-Key"

limits:
  default:
    rps: 20
    burst: 40
    cost: 1
  routes:
    "/read":
      rps: 2
      burst: 2
      cost: 1
    "/search":
      rps: 2
      burst: 2
      cost: 2
    "/api":
      rps: 2
      burst: 2
      cost: 1
  global_client:
    rps: 4
    burst: 4
    cost: 1

anomaly:
  enabled: true
  window_seconds: 10
  buckets: 10
  threshold_multiplier: 2.0
  ewma_alpha: 0.2
  ttl_seconds: 300 # evict keys idle > 5m
  evict_every_seconds: 30 # run janitor every 30s
  keep_suspicious_seconds: 600 # keep suspicious keys for 10m

mitigation:
  # global safety rails
  min_rps: 1            # never clamp below this
  min_burst: 5
  override_ttl_seconds: 180
  block_ttl_seconds: 120
  step_ramp:            # 50% -> 75% -> 100% style ramp
    enabled: true
    steps: [0.5, 0.75, 1.0]
    step_seconds: 45

  # escalation
  repeat_offender:
    window_seconds: 600   # M minutes
    threshold: 3          # N anomalies in window -> block

  # allowlist (no mitigation)
  allowlist:
    clients: ["1.2.3.4", "partner-key-abc"]


